package com.tweetapp.api.model;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.tweetapp.api.convertor.UserConvertor;
import com.tweetapp.api.convertor.tweetConvertor;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
;
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Tweet")
public class Tweet {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String tweet;
	@DynamoDBAttribute
	private String postDate;
	@DynamoDBAttribute
	private long likes;
	@DynamoDBTypeConverted(converter = UserConvertor.class)
	@DynamoDBAttribute
	private User user;
	@DynamoDBTypeConvertedEnum
	@DynamoDBTypeConverted(converter = tweetConvertor.class)
	@DynamoDBAttribute
	private List<Tweet> replies;
	@DynamoDBAttribute
	private String tweetTag;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getTweet() {
		return tweet;
	}
	public void setTweet(String tweet) {
		this.tweet = tweet;
	}
	public String getPostDate() {
		return postDate;
	}
	public void setPostDate(String postDate) {
		this.postDate = postDate;
	}
	public long getLikes() {
		return likes;
	}
	public void setLikes(long likes) {
		this.likes = likes;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}


	@Override
	public String toString() {
		return "Tweet [id=" + id + ", tweet=" + tweet + ", postDate=" + postDate + ", likes=" + likes + ", user=" + user
				+ ", replies=" + replies + ", tweetTag=" + tweetTag + "]";
	}
	public List<Tweet> getReplies() {
		return replies;
	}
	public void setReplies(List<Tweet> replies) {
		this.replies = replies;
	}
	public String getTweetTag() {
		return tweetTag;
	}
	public void setTweetTag(String tweetTag) {
		this.tweetTag = tweetTag;
	}

}
